development: &common_settings
  google_analytics_id: ~
  public_host: ~
  leaflet_key: ed5940a5e0724173aba9da0d77368912
  socrata_key: c1qN0TO6e65zh9oxVD6XrVJyT
  dstk_host: www.datasciencetoolkit.org
  bloom_api_db_url: postgres://bloomapi:bloomapi@localhost/bloomapi
  bloom_api_base_url: http://localhost:3000
  mongoid_config_file: config/mongoid.yml
  states:
    - Alabama
    - Alaska
    - Arizona
    - Arkansas
    - California
    - Colorado
    - Connecticut
    - Delaware
    - District Of Columbia
    # - Federated States Of Micronesia
    - Florida
    - Georgia
    # - Guam
    - Hawaii
    - Idaho
    - Illinois
    - Indiana
    - Iowa
    - Kansas
    - Kentucky
    - Louisiana
    - Maine
    # - Marshall Islands
    - Maryland
    - Massachusetts
    - Michigan
    - Minnesota
    - Mississippi
    - Missouri
    - Montana
    - Nebraska
    - Nevada
    - New Hampshire
    - New Jersey
    - New Mexico
    - New York
    - North Carolina
    - North Dakota
    - Ohio
    - Oklahoma
    - Oregon
    # - Palau
    - Pennsylvania
    # - Puerto Rico
    - Rhode Island
    - South Carolina
    - South Dakota
    - Tennessee
    - Texas
    - Utah
    - Vermont
    - Virginia
    - Washington
    - West Virginia
    - Wisconsin
    - Wyoming

production:
  <<: *common_settings
  google_analytics_id: UA-31592977-6 # override the default value
  public_host: ~
  cache_time: 7200 # used for static assets and all routes
  bloom_api_db_url: false
  bloom_api_base_url: false