development: &common_settings
  google_analytics_id: ~ # (null)
  public_host: ''
  leaflet_key: 'ed5940a5e0724173aba9da0d77368912'

production:
  <<: *common_settings
  google_analytics_id: 'UA-31592977-6' # override the default value